language: node_js
node_js:
- '6.0'
addons:
  hosts:
    - rabbit
    - hare
services:
  - rabbitmq
install:
    - sudo rabbitmq-plugins enable rabbitmq_management
    - sudo service rabbitmq-server restart
    - npm install
